[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "ieapp-core"
requires-python = ">=3.12"
dependencies = []
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "ieapp_core._ieapp_core"
